main:
	g++ -I src/include -L src/lib -o main main.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf

test:
	g++ -I src/include -L src/lib -o test test.cpp -lmingw32 -lSDL2test -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf